### ISSUE TITLE
InitialConditions:originTime must be numeric

### ISSUE THREAD

**Issue by wychao2** [PoonLab/twt#104]
I'm getting this error

```R
Error in private$load.initial.conds(settings) : 
  InitialConditions:originTime must be numeric; is this key missing?
```
when calling 

```R
model <- Model$new(yaml.load_file(path))
```
Currently, I have the YAML file set the same as the one in the tests folder:
```YAML
InitialConditions:
  originTime: 10.0  # note this is reverse time, cumulative
  size:
    host: 1000  # number of susceptible at the origin time of the simulation for Type `host`
  indexType: 'host'
```
