### ISSUE TITLE
Mismatch b/w compartment names

### ISSUE THREAD

**Issue by davidchampredon** [PoonLab/twt#105]
Got this error `Error in sim.inner.tree(obj = m, e = evlog) : 
  Mismatch between compartment names in Run and EventLogger objects.` when running this example below. 

When debugging inside `simInnerTree.R` the name comparison fails because the names retrieved from the `run$get.compartments()` and `run$get.unsampled.hosts()` functions append the string `_1` (i.e., `ID123_1`) whereas the `events$compartment1/2` function returns the raw compartment name (i.e. `ID123` only). I don't know how to fix this... Likely my YAML file (below), but it looks compliant (when compared to the documentation example).

Thanks.

MRE:
``` r
library(twt)
set.seed(1234)

# Outer tree 
settings <- yaml.load_file('../data/sampled-hosts-1.yaml')
# Set-up twt model:
m <- Model$new(settings)

# import outer tree from 
# outside simulation (e.g., ABM)
outer.tree <- ape::read.tree('../data/transm.nwk')
evlog <- eventlog.from.tree(tree = outer.tree)

# Simulate inner tree:
inner <- sim.inner.tree(obj = m, e = evlog)
# >> ERROR:
# >> "Mismatch between compartment names in Run and EventLogger objects."
```

YAML:

``` yaml
InitialConditions:
  originTime: 3493
  size:
    host: 560
  indexType: 'host'

CompartmentTypes:
  'host':
    migration.rates: ()
    transition.rates: ()
    branching.rates: (host=0.01)
    coalescent.rate: 1.2
    bottleneck.size: 1
    wait.time.distr:
      distr: 'exp'
      hyperparameters:
        - rate: 0.001
    popn.growth.dynamics:
      piece1:
        - startTime: 0
        - startPopn: 1
        - endTime: 5
        - endPopn: 20
      piece2:
        - startTime: 5
        - startPopn: 10

LineageTypes:
 'virus':

Compartments:
  'ID221':
    type: host
    source: 'ID277'
    branching.time: 2556
    replicates: 1
  'ID190':
    type: host
    source: 'ID221'
    branching.time: 2129
    replicates: 1
  'ID105':
    type: host
    source: 'ID18'
    branching.time: 1564
    replicates: 1
  'ID188':
    type: host
    source: 'ID105'
    branching.time: 1553
    replicates: 1
  'ID406':
    type: host
    source: 'ID105'
    branching.time: 1549
    replicates: 1
  'ID207':
    type: host
    source: 'ID192'
    branching.time: 1534
    replicates: 1
  'ID56':
    type: host
    source: 'ID192'
    branching.time: 1524
    replicates: 1
  'ID228':
    type: host
    source: 'ID218'
    branching.time: 1508
    replicates: 1
  'ID149':
    type: host
    source: 'ID57'
    branching.time: 1505
    replicates: 1
  'ID1':
    type: host
    source: 'ID233'
    branching.time: 1271
    replicates: 1
  'ID463':
    type: host
    source: 'ID84'
    branching.time: 1229
    replicates: 1
  'ID389':
    type: host
    source: 'ID56'
    branching.time: 1227
    replicates: 1
  'ID21':
    type: host
    source: 'ID295'
    branching.time: 748
    replicates: 1
  'ID210':
    type: host
    source: 'ID73'
    branching.time: 592
    replicates: 1
  'ID426':
    type: host
    source: 'ID335'
    branching.time: 569
    replicates: 1
  'ID316':
    type: host
    source: 'ID183'
    branching.time: 519
    replicates: 1
  'ID553':
    type: host
    source: 'ID426'
    branching.time: 505
    replicates: 1
  'ID274':
    type: host
    source: 'ID229'
    branching.time: 401
    replicates: 1
  'ID430':
    type: host
    source: 'ID235'
    branching.time: 344
    replicates: 1
  'ID337':
    type: host
    source: 'ID152'
    branching.time: 279
    replicates: 1

Lineages:
  '1':
    type: virus
    sampling.time: 1263
    location: 'ID221'
    replicates: 1
  '2':
    type: virus
    sampling.time: 483
    location: 'ID190'
    replicates: 1
  '3':
    type: virus
    sampling.time: 1280
    location: 'ID105'
    replicates: 1
  '4':
    type: virus
    sampling.time: 183
    location: 'ID188'
    replicates: 1
  '5':
    type: virus
    sampling.time: 156
    location: 'ID406'
    replicates: 1
  '6':
    type: virus
    sampling.time: 1467
    location: 'ID207'
    replicates: 1
  '7':
    type: virus
    sampling.time: 1021
    location: 'ID56'
    replicates: 1
  '8':
    type: virus
    sampling.time: 1486
    location: 'ID228'
    replicates: 1
  '9':
    type: virus
    sampling.time: 1130
    location: 'ID149'
    replicates: 1
  '10':
    type: virus
    sampling.time: 329
    location: 'ID1'
    replicates: 1
  '11':
    type: virus
    sampling.time: 831
    location: 'ID463'
    replicates: 1
  '12':
    type: virus
    sampling.time: 571
    location: 'ID389'
    replicates: 1
  '13':
    type: virus
    sampling.time: 706
    location: 'ID21'
    replicates: 1
  '14':
    type: virus
    sampling.time: 223
    location: 'ID210'
    replicates: 1
  '15':
    type: virus
    sampling.time: 492
    location: 'ID426'
    replicates: 1
  '16':
    type: virus
    sampling.time: 0
    location: 'ID316'
    replicates: 1
  '17':
    type: virus
    sampling.time: 497
    location: 'ID553'
    replicates: 1
  '18':
    type: virus
    sampling.time: 38
    location: 'ID274'
    replicates: 1
  '19':
    type: virus
    sampling.time: 307
    location: 'ID430'
    replicates: 1
  '20':
    type: virus
    sampling.time: 102
    location: 'ID337'
    replicates: 1

```

**Comment by ArtPoon** [comment]
Can you post the newick tree please?

**Comment by davidchampredon** [comment]
sorry forgot about this one... Here it is:

```
(((ID73:1233,(ID352:1106,ID62:1106)ID352:127)ID73:866,(ID210:1874,ID104:1874)ID210:225)ID73:2395,(((ID18:3071,((((ID105:1413,ID552:1413)ID105:1508,(ID84:2736,((ID463:517,(((ID633:267,(((ID559:257,((ID438:245,ID325:245)ID438:2,(ID76:229,ID198:229)ID76:18)ID438:10)ID559:2,ID341:259)ID559:5,ID518:264)ID559:3)ID633:230,ID356:497)ID633:11,ID548:508)ID633:9)ID463:1953,((ID372:2459,(ID474:2100,((ID529:282,ID540:282)ID529:1302,ID560:1584)ID529:516)ID474:359)ID372:6,(ID214:1063,(ID10:474,ID605:474)ID10:589)ID214:1402)ID372:5)ID463:266)ID84:185)ID105:135,(ID406:2826,ID237:2826)ID406:230)ID105:4,((((ID188:334,ID584:334)ID188:35,((ID161:11,ID13:11)ID161:344,ID371:355)ID161:14)ID188:2678,ID97:3047)ID188:2,(((ID192:2016,(ID61:1419,(((ID449:898,ID112:898)ID449:275,(ID619:140,ID718:140)ID619:1033)ID449:235,((ID215:129,ID714:129)ID215:1114,ID141:1243)ID215:165)ID449:11)ID61:597)ID192:1015,((ID56:2734,ID389:2734)ID56:292,((((ID57:1844,((ID113:1157,ID590:1157)ID113:143,(((ID50:1166,(ID384:1159,ID163:1159)ID384:7)ID50:125,(ID466:628,ID717:628)ID466:663)ID50:1,((((ID28:63,(ID422:51,(ID355:45,ID496:45)ID355:6)ID422:12)ID28:1192,(ID219:997,ID336:997)ID219:258)ID28:25,ID118:1280)ID28:3,(ID40:1278,ID11:1278)ID40:5)ID28:9)ID50:8)ID113:544)ID57:78,(ID102:1917,((((((ID229:325,(ID400:320,((ID154:314,ID706:314)ID154:1,((ID456:155,(ID748:9,(ID490:2,ID539:2)ID490:7)ID748:146)ID456:153,(ID243:284,ID39:284)ID243:24)ID456:7)ID154:5)ID400:5)ID229:270,(ID176:583,ID293:583)ID176:12)ID229:412,ID306:1007)ID229:271,(ID500:655,ID568:655)ID500:623)ID229:626,ID191:1904)ID229:4,ID274:1908)ID229:9)ID102:5)ID57:1090,((ID149:15,ID305:15)ID149:177,ID142:192)ID149:2820)ID57:6,(((ID218:3011,((ID235:1851,((ID430:1092,ID627:1092)ID430:740,ID117:1832)ID430:19)ID235:1144,((ID281:989,ID460:989)ID281:1996,((((ID288:1225,(ID65:217,ID451:217)ID65:1008)ID288:1730,((ID260:1058,ID58:1058)ID260:1885,ID418:2943)ID260:12)ID288:11,((ID152:1632,ID33:1632)ID152:154,(ID337:1183,ID565:1183)ID337:603)ID152:1180)ID288:15,(ID233:2778,ID1:2778)ID233:203)ID288:4)ID281:10)ID235:16)ID218:4,(ID335:2076,((ID426:1366,((ID42:406,ID47:406)ID42:956,(ID205:1355,ID217:1355)ID205:7)ID42:4)ID426:646,ID553:2012)ID426:64)ID335:939)ID218:0,(ID228:1457,(ID360:452,ID541:452)ID360:1005)ID228:1558)ID218:3)ID57:8)ID56:5)ID192:10,((ID207:996,ID488:996)ID207:393,(ID391:584,ID179:584)ID391:805)ID207:1652)ID192:8)ID188:11)ID105:11)ID18:997,(ID165:397,(ID467:384,ID482:384)ID467:13)ID165:3671)ID18:421,((((ID277:1137,ID285:1137)ID277:898,(((ID183:595,ID370:595)ID183:222,(ID620:342,ID741:342)ID620:475)ID183:1209,ID316:2026)ID183:9)ID277:721,((ID212:2273,(((ID295:2249,ID225:2249)ID295:6,(ID21:861,ID290:861)ID21:1394)ID295:11,(ID100:326,((ID151:314,ID439:314)ID151:1,ID246:315)ID151:11)ID100:1940)ID295:7)ID212:203,ID93:2476)ID212:280)ID277:1307,((ID221:3039,(ID399:955,ID574:955)ID399:2084)ID221:597,(ID190:681,ID464:681)ID190:2955)ID221:427)ID277:426)ID18:5)ID73:506;
```

**Comment by ArtPoon** [comment]
Got it.  `twt` automatically adds a `_1` suffix to Compartment object names:
```R
> names(comps)
 [1] "ID221_1" "ID190_1" "ID105_1" "ID188_1" "ID406_1" "ID207_1" "ID56_1" 
 [8] "ID228_1" "ID149_1" "ID1_1"   "ID463_1" "ID389_1" "ID21_1"  "ID210_1"
[15] "ID426_1" "ID316_1" "ID553_1" "ID274_1" "ID430_1" "ID337_1"
> head(events)
    event.type time lineage1 lineage2 compartment1 compartment2 type1 type2
1 transmission 1233       NA       NA        ID352         ID73    NA    NA
2 transmission 1106       NA       NA         ID62        ID352    NA    NA
3 transmission 2099       NA       NA        ID210         ID73    NA    NA
4 transmission 1874       NA       NA        ID104        ID210    NA    NA
5 transmission 4494       NA       NA         ID18         ID73    NA    NA
6 transmission 3071       NA       NA        ID105         ID18    NA    NA
```

**Comment by ArtPoon** [comment]
Running into a different problem:
```R
Error in .resolve.transmission(run, e) : 
  resolve.transmission() failed to locate recipient Compartment ID539_1
```
This compartment has not been initialized because we have only generated sampled Compartments from the tips of the outer tree.  `ID539_1` is an unsampled named Compartment.  We have to create unsampled Compartments in the Run object accordingly.

**Comment by ArtPoon** [comment]
Based on #107, it is up to the user to specify unsampled Source individuals in the YAML file.
I have modified `Model:load_compartments()` so that it interprets the label `unsampled` in the YAML.
For example, the second entry below is an unsampled source Compartment:
```yaml
  'ID337':
    type: host
    source: 'ID152'
    branching.time: 279
    replicates: 1
  'ID539':
    type: host
    source: 'ID490'
    branching.time: 1000
    unsampled: TRUE
```
