### ISSUE TITLE
Time to simulate inner tree is long

### ISSUE THREAD

**Issue by wychao2** [PoonLab/twt#108]
It took 4.11105 hours to simulate the inner tree with the parameters specified in this YAML file. 

```YAML
InitialConditions:
    originTime: 10  # duration of simulation
    size:
        S0: 8999
        S1: 1000
    indexType: S0

CompartmentTypes:
    'S0':
        branching.rates: (S0=0.005, S1=0.005) 
        transition.rates: (S0=0.0, S1=0.007)
        migration.rates: ()
        coalescent.rate: 0.01
        bottleneck.size: 1  
        wait.time.distr:
        distr: 'exp'
        hyperparameters:
            rate: 20
   
    'S1':
        branching.rates: (S0=0.03, S1=0.03) 
        transition.rates: (S0=0.007, S1=0.0)
        migration.rates: ()
        coalescent.rate: 0.01
        bottleneck.size: 1  
        wait.time.distr:
        distr: 'exp'
        hyperparameters:
            rate: 20


Compartments:
    'I0':
        type: S0
        replicates: 500

    'I1':
        type: S1
        replicates: 500
    
    'I0-10':
        type: S0
        replicates: 1

Lineages:
    'I0':
        type: virus
        sampling.time: (3.0)
        location: I0
        replicates: 1

    'I1':
        type: virus
        sampling.time: (3.0)
        location: I1
        replicates: 1

    'I0-10':
        type: virus
        sampling.time: (0.0)
        location: I0
        replicates: 1


```
