### ISSUE TITLE
too lax load.outer.tree()?

### ISSUE THREAD

**Issue by davidchampredon** [PoonLab/twt#109]
Hi @ArtPoon ,
I'm loading an outer tree from a YAML file with `load.outer.tree`. No error messages, `print` and `class` seem OK, but `plot` doesn't work as well as inner tree simulation. Very likely something is wrong on my side but can't spot it. Maybe `load.outer.tree` should catch whatever mistake I make? 

Below are the MRE and YAML file used.
Thanks! 

``` r
library(twt)
set.seed(1234)

# Set-up twt model:
settings <- yaml.load_file('../data/sampled-hosts-1.yaml')
m        <- Model$new(settings)

# Load outer tree (ABM's output):
outer.tree <- twt::load.outer.tree(model = m)
class(outer.tree) # looks OK
print(outer.tree) # looks OK

# But this fails:
plot(outer.tree)
# >> Error in max(sapply(comp$get.lineages(), function(line) line$get.sampling.time())) : 
#     invalid 'type' (list) of argument
#    Called from: .plot.outer.tree(run, ...)

# This fails too:
inner <- sim.inner.tree(obj = outer)
# >>  Error in sim.inner.tree(obj = outer) : 
#     sim.inner.tree(): argument `mod` must be R6 class Model or Run.
```

YAML file: 

``` yaml
InitialConditions:
  originTime: 3540
  size:
    host: 6061
  indexType: 'host'

CompartmentTypes:
  'host':
    migration.rates: ()
    transition.rates: ()
    branching.rates: (host=1e-06)
    coalescent.rate: 1.2
    bottleneck.size: 1
    wait.time.distr:
      distr: 'exp'
      hyperparameters:
        - rate: 0.001
    popn.growth.dynamics:
      piece1:
        - startTime: 0
        - startPopn: 1
        - endTime: 5
        - endPopn: 20
      piece2:
        - startTime: 5
        - startPopn: 10

LineageTypes:
 'virus':

Compartments:
  'ID2644':
    type: host
    source: 'NA'
    branching.time: NA
    replicates: 1
  'ID717':
    type: host
    source: 'ID2644'
    branching.time: 3037
    unsampled: TRUE
  'ID2095':
    type: host
    source: 'ID717'
    branching.time: 2829
    unsampled: TRUE
  'ID1675':
    type: host
    source: 'ID2095'
    branching.time: 2711
    replicates: 1
  'ID2101':
    type: host
    source: 'ID1675'
    branching.time: 2700
    replicates: 1
  'ID2151':
    type: host
    source: 'ID717'
    branching.time: 2687
    replicates: 1
  'ID515':
    type: host
    source: 'ID2101'
    branching.time: 2686
    replicates: 1
  'ID3201':
    type: host
    source: 'ID2151'
    branching.time: 2651
    replicates: 1
  'ID935':
    type: host
    source: 'ID2101'
    branching.time: 2573
    unsampled: TRUE
  'ID3819':
    type: host
    source: 'ID717'
    branching.time: 2273
    unsampled: TRUE
  'ID1596':
    type: host
    source: 'ID935'
    branching.time: 2003
    replicates: 1
  'ID791':
    type: host
    source: 'ID1596'
    branching.time: 1994
    unsampled: TRUE
  'ID692':
    type: host
    source: 'ID791'
    branching.time: 1979
    replicates: 1
  'ID2313':
    type: host
    source: 'ID3819'
    branching.time: 1822
    unsampled: TRUE
  'ID849':
    type: host
    source: 'ID2644'
    branching.time: 1398
    unsampled: TRUE
  'ID4128':
    type: host
    source: 'ID2313'
    branching.time: 1350
    replicates: 1
  'ID1843':
    type: host
    source: 'ID515'
    branching.time: 1236
    unsampled: TRUE
  'ID3327':
    type: host
    source: 'ID1843'
    branching.time: 1222
    replicates: 1
  'ID2832':
    type: host
    source: 'ID3327'
    branching.time: 1112
    unsampled: TRUE
  'ID4415':
    type: host
    source: 'ID1596'
    branching.time: 913
    unsampled: TRUE
  'ID3868':
    type: host
    source: 'ID4415'
    branching.time: 904
    unsampled: TRUE
  'ID950':
    type: host
    source: 'ID4128'
    branching.time: 853
    unsampled: TRUE
  'ID2806':
    type: host
    source: 'ID950'
    branching.time: 850
    unsampled: TRUE
  'ID1226':
    type: host
    source: 'ID2806'
    branching.time: 841
    unsampled: TRUE
  'ID5111':
    type: host
    source: 'ID1596'
    branching.time: 706
    unsampled: TRUE
  'ID2624':
    type: host
    source: 'ID3819'
    branching.time: 567
    unsampled: TRUE
  'ID3755':
    type: host
    source: 'ID4128'
    branching.time: 470
    unsampled: TRUE
  'ID3191':
    type: host
    source: 'ID2806'
    branching.time: 386
    replicates: 1
  'ID2865':
    type: host
    source: 'ID2095'
    branching.time: 335
    unsampled: TRUE
  'ID3488':
    type: host
    source: 'ID2865'
    branching.time: 327
    replicates: 1
  'ID2895':
    type: host
    source: 'ID3488'
    branching.time: 313
    replicates: 1
  'ID3937':
    type: host
    source: 'ID3201'
    branching.time: 123
    unsampled: TRUE
  'ID1029':
    type: host
    source: 'ID3937'
    branching.time: 81
    unsampled: TRUE
  'ID2867':
    type: host
    source: 'ID1029'
    branching.time: 67
    unsampled: TRUE
  'ID843':
    type: host
    source: 'ID3488'
    branching.time: 18
    unsampled: TRUE
  'ID4245':
    type: host
    source: 'ID843'
    branching.time: 11
    unsampled: TRUE
  'ID5067':
    type: host
    source: 'ID843'
    branching.time: 7
    unsampled: TRUE
  'ID5265':
    type: host
    source: 'ID4245'
    branching.time: 5
    replicates: 1

Lineages:
  '1':
    type: virus
    sampling.time: 2722
    location: ID2644
    replicates: 1
  '2':
    type: virus
    sampling.time: 2162
    location: ID1675
    replicates: 1
  '3':
    type: virus
    sampling.time: 1997
    location: ID2101
    replicates: 1
  '4':
    type: virus
    sampling.time: 6
    location: ID2151
    replicates: 1
  '5':
    type: virus
    sampling.time: 505
    location: ID515
    replicates: 1
  '6':
    type: virus
    sampling.time: 1176
    location: ID3201
    replicates: 1
  '7':
    type: virus
    sampling.time: 699
    location: ID1596
    replicates: 1
  '8':
    type: virus
    sampling.time: 1357
    location: ID692
    replicates: 1
  '9':
    type: virus
    sampling.time: 501
    location: ID4128
    replicates: 1
  '10':
    type: virus
    sampling.time: 814
    location: ID3327
    replicates: 1
  '11':
    type: virus
    sampling.time: 185
    location: ID3191
    replicates: 1
  '12':
    type: virus
    sampling.time: 95
    location: ID3488
    replicates: 1
  '13':
    type: virus
    sampling.time: 154
    location: ID2895
    replicates: 1
  '14':
    type: virus
    sampling.time: 0
    location: ID5265
    replicates: 1
```

**Comment by ArtPoon** [comment]
Reproduced problem:
```R
> require(twt)
> set.seed(1234)
> settings <- yaml.load_file('~/git/twt/working/sampled-hosts-1.yaml')
> model <- Model$new(settings)
> run <- load.outer.tree(model)
> plot(run, type='s')
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
```

All compartments are named:
```R
> comps <- run$get.compartments()
> events <- run$get.eventlog()$get.all.events()
> 
> nodes <- unique(c(events$compartment1, events$compartment2))
> all(is.element(nodes, names(comps)))
[1] TRUE
```

**Comment by ArtPoon** [comment]
The problem is that you have unsampled compartments returned from `run$get.compartments()`.
Since the compartment is unsampled, it is not carrying any Lineage objects and the following line fails:
```R
      samp.time <- -max(sapply(comp$get.lineages(), 
                              function(line) line$get.sampling.time()))
```

**Comment by ArtPoon** [comment]
The other problem is caused by a recent change to defining CompartmentTypes, where the user has to specify a generation time to scale from inner to outer dynamics.

**Comment by ArtPoon** [comment]
```yaml
InitialConditions:
  originTime: 3540
  size:
    host: 6061
  indexType: 'host'

CompartmentTypes:
  'host':
    migration.rates: ()
    transition.rates: ()
    branching.rates: (host=1e-06)
    effective.size: 100
    generation.time: 1
    bottleneck.size: 1
    popn.growth.dynamics:
      piece1:
        - startTime: 0
        - startPopn: 1
        - endTime: 5
        - endPopn: 20
      piece2:
        - startTime: 5
        - startPopn: 10
```
