### ISSUE TITLE
Change YAML specification for rates

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#115]
Currently we use the following format:
```yaml
CompartmentTypes:
  'host1':
    branching.rates: (host1=1e-4, host2=2e-5)
    transition.rates: (host1=0, host2=0.01)
    migration.rates: (host1=5e-5, host2=1e-5)
    effective.size: 100
    generation.time: 0.01
    bottleneck.size: 1
  'host2':
    branching.rates: (host1=2e-5, host2=1e-4)
    transition.rates: (host1=0.01, host2=0)
    migration.rates: (host1=1e-5, host2=5e-5)
    effective.size: 100
    generation.time: 0.01
    bottleneck.size: 1
```

I would like to change this to:
```yaml
CompartmentTypes:
  'host1':
    branching.rates:
      host1: 1e-4
      host2: 2e-5
    transition.rates: 
      host1: 0
      host2: 0.01
    migration.rates: 
      host1: 5e-5
      host2: 1e-5
    effective.size: 100
    generation.time: 0.01
    bottleneck.size: 1
```
