### ISSUE TITLE
No eligible compartments for transmission event

### ISSUE THREAD

**Issue by wychao2** [PoonLab/twt#117]
When specifying sampling times closer to the start of the epidemic twt fails with this error. 

```R
 Error in .assign.events(run, events) : 
  Error in .assign.events(): No eligible compartments for transmission event 7.531464584365922S0S00090199
```

Mean sample time for this run was set to 8, entire simulation had a run length of 10. 

```YAML
InitialConditions:
 originTime: 10
 size:
  S0: 900
  S1: 100
 indexType: S0

CompartmentTypes:
 'S0':
  branching.rates: (S0=0.005, S1=0.005)
  transition.rates: (S0=0.0, S1=0.0005)
  migration.rates: ()
  bottleneck.size: 1
  generation.time: 0.001
  effective.size: 900

 'S1':
  branching.rates: (S0=0.01, S1=0.01)
  transition.rates: (S0=0.005, S1=0.0)
  migration.rates: ()
  bottleneck.size: 1
  generation.time: 0.001
  effective.size: 100

Compartments:
 'I0-1':
  type: S0
  replicates: 1

 'I1-1':
  type: S1
  replicates: 1

 'I0-2':
  type: S0
  replicates: 1

 'I1-2':
  type: S1
  replicates: 1

 'I0-3':
  type: S0
  replicates: 1

 'I1-3':
  type: S1
  replicates: 1

 'I0-4':
  type: S0
  replicates: 1

 'I1-4':
  type: S1
  replicates: 1

 'I0-5':
  type: S0
  replicates: 1

 'I1-5':
  type: S1
  replicates: 1

 'I0-6':
  type: S0
  replicates: 1

 'I1-6':
  type: S1
  replicates: 1

 'I0-7':
  type: S0
  replicates: 1

 'I1-7':
  type: S1
  replicates: 1

 'I0-8':
  type: S0
  replicates: 1

 'I1-8':
  type: S1
  replicates: 1

 'I0-9':
  type: S0
  replicates: 1

 'I1-9':
  type: S1
  replicates: 1

 'I0-10':
  type: S0
  replicates: 1

 'I1-10':
  type: S1
  replicates: 1

 'I0-11':
  type: S0
  replicates: 1

 'I1-11':
  type: S1
  replicates: 1

 'I0-12':
  type: S0
  replicates: 1

 'I1-12':
  type: S1
  replicates: 1

 'I0-13':
  type: S0
  replicates: 1

 'I1-13':
  type: S1
  replicates: 1

 'I0-14':
  type: S0
  replicates: 1

 'I1-14':
  type: S1
  replicates: 1

 'I0-15':
  type: S0
  replicates: 1

 'I1-15':
  type: S1
  replicates: 1

 'I0-16':
  type: S0
  replicates: 1

 'I1-16':
  type: S1
  replicates: 1

 'I0-17':
  type: S0
  replicates: 1

 'I1-17':
  type: S1
  replicates: 1

 'I0-18':
  type: S0
  replicates: 1

 'I1-18':
  type: S1
  replicates: 1

 'I0-19':
  type: S0
  replicates: 1

 'I1-19':
  type: S1
  replicates: 1

 'I0-20':
  type: S0
  replicates: 1

 'I1-20':
  type: S1
  replicates: 1

 'I0-21':
  type: S0
  replicates: 1

 'I1-21':
  type: S1
  replicates: 1

 'I0-22':
  type: S0
  replicates: 1

 'I1-22':
  type: S1
  replicates: 1

 'I0-23':
  type: S0
  replicates: 1

 'I1-23':
  type: S1
  replicates: 1

 'I0-24':
  type: S0
  replicates: 1

 'I1-24':
  type: S1
  replicates: 1

 'I0-25':
  type: S0
  replicates: 1

 'I1-25':
  type: S1
  replicates: 1

 'I0-26':
  type: S0
  replicates: 1

 'I1-26':
  type: S1
  replicates: 1

 'I0-27':
  type: S0
  replicates: 1

 'I1-27':
  type: S1
  replicates: 1

 'I0-28':
  type: S0
  replicates: 1

 'I1-28':
  type: S1
  replicates: 1

 'I0-29':
  type: S0
  replicates: 1

 'I1-29':
  type: S1
  replicates: 1

 'I0-30':
  type: S0
  replicates: 1

 'I1-30':
  type: S1
  replicates: 1

 'I0-31':
  type: S0
  replicates: 1

 'I1-31':
  type: S1
  replicates: 1

 'I0-32':
  type: S0
  replicates: 1

 'I1-32':
  type: S1
  replicates: 1

 'I0-33':
  type: S0
  replicates: 1

 'I1-33':
  type: S1
  replicates: 1

 'I0-34':
  type: S0
  replicates: 1

 'I1-34':
  type: S1
  replicates: 1

 'I0-35':
  type: S0
  replicates: 1

 'I1-35':
  type: S1
  replicates: 1

 'I0-36':
  type: S0
  replicates: 1

 'I1-36':
  type: S1
  replicates: 1

 'I0-37':
  type: S0
  replicates: 1

 'I1-37':
  type: S1
  replicates: 1

 'I0-38':
  type: S0
  replicates: 1

 'I1-38':
  type: S1
  replicates: 1

 'I0-39':
  type: S0
  replicates: 1

 'I1-39':
  type: S1
  replicates: 1

 'I0-40':
  type: S0
  replicates: 1

 'I1-40':
  type: S1
  replicates: 1

 'I0-41':
  type: S0
  replicates: 1

 'I1-41':
  type: S1
  replicates: 1

 'I0-42':
  type: S0
  replicates: 1

 'I1-42':
  type: S1
  replicates: 1

 'I0-43':
  type: S0
  replicates: 1

 'I1-43':
  type: S1
  replicates: 1

 'I0-44':
  type: S0
  replicates: 1

 'I1-44':
  type: S1
  replicates: 1

 'I0-45':
  type: S0
  replicates: 1

 'I1-45':
  type: S1
  replicates: 1

 'I0-46':
  type: S0
  replicates: 1

 'I1-46':
  type: S1
  replicates: 1

 'I0-47':
  type: S0
  replicates: 1

 'I1-47':
  type: S1
  replicates: 1

 'I0-48':
  type: S0
  replicates: 1

 'I1-48':
  type: S1
  replicates: 1

 'I0-49':
  type: S0
  replicates: 1

 'I1-49':
  type: S1
  replicates: 1

 'I0-50':
  type: S0
  replicates: 1

 'I1-50':
  type: S1
  replicates: 1

Lineages:
 'I0-sampletime-8.12506562918679':
  type: virus
  sampling.time: (8.12506562918679)
  location: I0-1
  replicates: 1

 'I1-sampletime-8.12506562918679':
  type: virus
  sampling.time: (8.12506562918679)
  location: I1-1
  replicates: 1

 'I0-sampletime-8.09186213575249':
  type: virus
  sampling.time: (8.09186213575249)
  location: I0-2
  replicates: 1

 'I1-sampletime-8.09186213575249':
  type: virus
  sampling.time: (8.09186213575249)
  location: I1-2
  replicates: 1

 'I0-sampletime-8.15849043517972':
  type: virus
  sampling.time: (8.15849043517972)
  location: I0-3
  replicates: 1

 'I1-sampletime-8.15849043517972':
  type: virus
  sampling.time: (8.15849043517972)
  location: I1-3
  replicates: 1

 'I0-sampletime-7.95661288434856':
  type: virus
  sampling.time: (7.95661288434856)
  location: I0-4
  replicates: 1

 'I1-sampletime-7.95661288434856':
  type: virus
  sampling.time: (7.95661288434856)
  location: I1-4
  replicates: 1

 'I0-sampletime-8.03179083983867':
  type: virus
  sampling.time: (8.03179083983867)
  location: I0-5
  replicates: 1

 'I1-sampletime-8.03179083983867':
  type: virus
  sampling.time: (8.03179083983867)
  location: I1-5
  replicates: 1

 'I0-sampletime-8.12051728731542':
  type: virus
  sampling.time: (8.12051728731542)
  location: I0-6
  replicates: 1

 'I1-sampletime-8.12051728731542':
  type: virus
  sampling.time: (8.12051728731542)
  location: I1-6
  replicates: 1

 'I0-sampletime-8.11585373365401':
  type: virus
  sampling.time: (8.11585373365401)
  location: I0-7
  replicates: 1

 'I1-sampletime-8.11585373365401':
  type: virus
  sampling.time: (8.11585373365401)
  location: I1-7
  replicates: 1

 'I0-sampletime-8.13336924909037':
  type: virus
  sampling.time: (8.13336924909037)
  location: I0-8
  replicates: 1

 'I1-sampletime-8.13336924909037':
  type: virus
  sampling.time: (8.13336924909037)
  location: I1-8
  replicates: 1

 'I0-sampletime-7.92081390747303':
  type: virus
  sampling.time: (7.92081390747303)
  location: I0-9
  replicates: 1

 'I1-sampletime-7.92081390747303':
  type: virus
  sampling.time: (7.92081390747303)
  location: I1-9
  replicates: 1

 'I0-sampletime-7.90291717250763':
  type: virus
  sampling.time: (7.90291717250763)
  location: I0-10
  replicates: 1

 'I1-sampletime-7.90291717250763':
  type: virus
  sampling.time: (7.90291717250763)
  location: I1-10
  replicates: 1

 'I0-sampletime-8.02077270642753':
  type: virus
  sampling.time: (8.02077270642753)
  location: I0-11
  replicates: 1

 'I1-sampletime-8.02077270642753':
  type: virus
  sampling.time: (8.02077270642753)
  location: I1-11
  replicates: 1

 'I0-sampletime-7.89902924492426':
  type: virus
  sampling.time: (7.89902924492426)
  location: I0-12
  replicates: 1

 'I1-sampletime-7.89902924492426':
  type: virus
  sampling.time: (7.89902924492426)
  location: I1-12
  replicates: 1

 'I0-sampletime-7.86125178983726':
  type: virus
  sampling.time: (7.86125178983726)
  location: I0-13
  replicates: 1

 'I1-sampletime-7.86125178983726':
  type: virus
  sampling.time: (7.86125178983726)
  location: I1-13
  replicates: 1

 'I0-sampletime-7.96357385352683':
  type: virus
  sampling.time: (7.96357385352683)
  location: I0-14
  replicates: 1

 'I1-sampletime-7.96357385352683':
  type: virus
  sampling.time: (7.96357385352683)
  location: I1-14
  replicates: 1

 'I0-sampletime-7.87133624945088':
  type: virus
  sampling.time: (7.87133624945088)
  location: I0-15
  replicates: 1

 'I1-sampletime-7.87133624945088':
  type: virus
  sampling.time: (7.87133624945088)
  location: I1-15
  replicates: 1

 'I0-sampletime-7.97599870393691':
  type: virus
  sampling.time: (7.97599870393691)
  location: I0-16
  replicates: 1

 'I1-sampletime-7.97599870393691':
  type: virus
  sampling.time: (7.97599870393691)
  location: I1-16
  replicates: 1

 'I0-sampletime-7.94823251176769':
  type: virus
  sampling.time: (7.94823251176769)
  location: I0-17
  replicates: 1

 'I1-sampletime-7.94823251176769':
  type: virus
  sampling.time: (7.94823251176769)
  location: I1-17
  replicates: 1

 'I0-sampletime-8.01468137480963':
  type: virus
  sampling.time: (8.01468137480963)
  location: I0-18
  replicates: 1

 'I1-sampletime-8.01468137480963':
  type: virus
  sampling.time: (8.01468137480963)
  location: I1-18
  replicates: 1

 'I0-sampletime-8.05968286120359':
  type: virus
  sampling.time: (8.05968286120359)
  location: I0-19
  replicates: 1

 'I1-sampletime-8.05968286120359':
  type: virus
  sampling.time: (8.05968286120359)
  location: I1-19
  replicates: 1

 'I0-sampletime-8.05411074134817':
  type: virus
  sampling.time: (8.05411074134817)
  location: I0-20
  replicates: 1

 'I1-sampletime-8.05411074134817':
  type: virus
  sampling.time: (8.05411074134817)
  location: I1-20
  replicates: 1

 'I0-sampletime-7.94885447235334':
  type: virus
  sampling.time: (7.94885447235334)
  location: I0-21
  replicates: 1

 'I1-sampletime-7.94885447235334':
  type: virus
  sampling.time: (7.94885447235334)
  location: I1-21
  replicates: 1

 'I0-sampletime-7.76581486305136':
  type: virus
  sampling.time: (7.76581486305136)
  location: I0-22
  replicates: 1

 'I1-sampletime-7.76581486305136':
  type: virus
  sampling.time: (7.76581486305136)
  location: I1-22
  replicates: 1

 'I0-sampletime-8.05205054414554':
  type: virus
  sampling.time: (8.05205054414554)
  location: I0-23
  replicates: 1

 'I1-sampletime-8.05205054414554':
  type: virus
  sampling.time: (8.05205054414554)
  location: I1-23
  replicates: 1

 'I0-sampletime-7.89792976917938':
  type: virus
  sampling.time: (7.89792976917938)
  location: I0-24
  replicates: 1

 'I1-sampletime-7.89792976917938':
  type: virus
  sampling.time: (7.89792976917938)
  location: I1-24
  replicates: 1

 'I0-sampletime-8.03659834874851':
  type: virus
  sampling.time: (8.03659834874851)
  location: I0-25
  replicates: 1

 'I1-sampletime-8.03659834874851':
  type: virus
  sampling.time: (8.03659834874851)
  location: I1-25
  replicates: 1

 'I0-sampletime-7.88770575304959':
  type: virus
  sampling.time: (7.88770575304959)
  location: I0-26
  replicates: 1

 'I1-sampletime-7.88770575304959':
  type: virus
  sampling.time: (7.88770575304959)
  location: I1-26
  replicates: 1

 'I0-sampletime-8.16033139877428':
  type: virus
  sampling.time: (8.16033139877428)
  location: I0-27
  replicates: 1

 'I1-sampletime-8.16033139877428':
  type: virus
  sampling.time: (8.16033139877428)
  location: I1-27
  replicates: 1

 'I0-sampletime-7.92047301316694':
  type: virus
  sampling.time: (7.92047301316694)
  location: I0-28
  replicates: 1

 'I1-sampletime-7.92047301316694':
  type: virus
  sampling.time: (7.92047301316694)
  location: I1-28
  replicates: 1

 'I0-sampletime-7.8237663077933':
  type: virus
  sampling.time: (7.8237663077933)
  location: I0-29
  replicates: 1

 'I1-sampletime-7.8237663077933':
  type: virus
  sampling.time: (7.8237663077933)
  location: I1-29
  replicates: 1

 'I0-sampletime-7.90656318997605':
  type: virus
  sampling.time: (7.90656318997605)
  location: I0-30
  replicates: 1

 'I1-sampletime-7.90656318997605':
  type: virus
  sampling.time: (7.90656318997605)
  location: I1-30
  replicates: 1

 'I0-sampletime-7.97837804378165':
  type: virus
  sampling.time: (7.97837804378165)
  location: I0-31
  replicates: 1

 'I1-sampletime-7.97837804378165':
  type: virus
  sampling.time: (7.97837804378165)
  location: I1-31
  replicates: 1

 'I0-sampletime-7.95785526997722':
  type: virus
  sampling.time: (7.95785526997722)
  location: I0-32
  replicates: 1

 'I1-sampletime-7.95785526997722':
  type: virus
  sampling.time: (7.95785526997722)
  location: I1-32
  replicates: 1

 'I0-sampletime-8.05849018474494':
  type: virus
  sampling.time: (8.05849018474494)
  location: I0-33
  replicates: 1

 'I1-sampletime-8.05849018474494':
  type: virus
  sampling.time: (8.05849018474494)
  location: I1-33
  replicates: 1

 'I0-sampletime-8.02695989232592':
  type: virus
  sampling.time: (8.02695989232592)
  location: I0-34
  replicates: 1

 'I1-sampletime-8.02695989232592':
  type: virus
  sampling.time: (8.02695989232592)
  location: I1-34
  replicates: 1

 'I0-sampletime-7.99547572448836':
  type: virus
  sampling.time: (7.99547572448836)
  location: I0-35
  replicates: 1

 'I1-sampletime-7.99547572448836':
  type: virus
  sampling.time: (7.99547572448836)
  location: I1-35
  replicates: 1

 'I0-sampletime-7.90942119280933':
  type: virus
  sampling.time: (7.90942119280933)
  location: I0-36
  replicates: 1

 'I1-sampletime-7.90942119280933':
  type: virus
  sampling.time: (7.90942119280933)
  location: I1-36
  replicates: 1

 'I0-sampletime-7.98422872725499':
  type: virus
  sampling.time: (7.98422872725499)
  location: I0-37
  replicates: 1

 'I1-sampletime-7.98422872725499':
  type: virus
  sampling.time: (7.98422872725499)
  location: I1-37
  replicates: 1

 'I0-sampletime-8.01099689675643':
  type: virus
  sampling.time: (8.01099689675643)
  location: I0-38
  replicates: 1

 'I1-sampletime-8.01099689675643':
  type: virus
  sampling.time: (8.01099689675643)
  location: I1-38
  replicates: 1

 'I0-sampletime-8.00989824738063':
  type: virus
  sampling.time: (8.00989824738063)
  location: I0-39
  replicates: 1

 'I1-sampletime-8.00989824738063':
  type: virus
  sampling.time: (8.00989824738063)
  location: I1-39
  replicates: 1

 'I0-sampletime-8.00012811476818':
  type: virus
  sampling.time: (8.00012811476818)
  location: I0-40
  replicates: 1

 'I1-sampletime-8.00012811476818':
  type: virus
  sampling.time: (8.00012811476818)
  location: I1-40
  replicates: 1

 'I0-sampletime-8.24791795372541':
  type: virus
  sampling.time: (8.24791795372541)
  location: I0-41
  replicates: 1

 'I1-sampletime-8.24791795372541':
  type: virus
  sampling.time: (8.24791795372541)
  location: I1-41
  replicates: 1

 'I0-sampletime-8.07022929269966':
  type: virus
  sampling.time: (8.07022929269966)
  location: I0-42
  replicates: 1

 'I1-sampletime-8.07022929269966':
  type: virus
  sampling.time: (8.07022929269966)
  location: I1-42
  replicates: 1

 'I0-sampletime-8.01264002646093':
  type: virus
  sampling.time: (8.01264002646093)
  location: I0-43
  replicates: 1

 'I1-sampletime-8.01264002646093':
  type: virus
  sampling.time: (8.01264002646093)
  location: I1-43
  replicates: 1

 'I0-sampletime-7.96136626180513':
  type: virus
  sampling.time: (7.96136626180513)
  location: I0-44
  replicates: 1

 'I1-sampletime-7.96136626180513':
  type: virus
  sampling.time: (7.96136626180513)
  location: I1-44
  replicates: 1

 'I0-sampletime-8.05887014812335':
  type: virus
  sampling.time: (8.05887014812335)
  location: I0-45
  replicates: 1

 'I1-sampletime-8.05887014812335':
  type: virus
  sampling.time: (8.05887014812335)
  location: I1-45
  replicates: 1

 'I0-sampletime-8.13131554795212':
  type: virus
  sampling.time: (8.13131554795212)
  location: I0-46
  replicates: 1

 'I1-sampletime-8.13131554795212':
  type: virus
  sampling.time: (8.13131554795212)
  location: I1-46
  replicates: 1

 'I0-sampletime-7.7984040129404':
  type: virus
  sampling.time: (7.7984040129404)
  location: I0-47
  replicates: 1

 'I1-sampletime-7.7984040129404':
  type: virus
  sampling.time: (7.7984040129404)
  location: I1-47
  replicates: 1

 'I0-sampletime-7.80662797685054':
  type: virus
  sampling.time: (7.80662797685054)
  location: I0-48
  replicates: 1

 'I1-sampletime-7.80662797685054':
  type: virus
  sampling.time: (7.80662797685054)
  location: I1-48
  replicates: 1

 'I0-sampletime-7.99241013028829':
  type: virus
  sampling.time: (7.99241013028829)
  location: I0-49
  replicates: 1

 'I1-sampletime-7.99241013028829':
  type: virus
  sampling.time: (7.99241013028829)
  location: I1-49
  replicates: 1

 'I0-sampletime-10':
  type: virus
  sampling.time: (0.0)
  location: I0-50
  replicates: 1

 'I1-sampletime-10':
  type: virus
  sampling.time: (0.0)
  location: I1-50
  replicates: 1

```
