### ISSUE TITLE
Sampling a lineage multiple times

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/twt#131]
This issue relates to sampling a lineage multiple times during the time frame. The error message depends on the number of replicates in the 'I' compartment and the seed:
```
set.seed(1234) / set.seed(123) if running with 5 replicates

path <- '~/Documents/1_projects/bayroot/MultitimeLineageSampling.yaml'
model <- Model$new(yaml.load_file(path))

outer <- sim.outer.tree(model)
plot(outer, type='s')

inner <- sim.inner.tree(outer)
plot(inner)
```

With 1: outer$get.eventlog() shows no events to display
With 2: @sim.outer.tree(model) Error in .assign.events(run, events) : 
  Error in .assign.events(): No eligible compartments for transmission event 1.068426060386581hosthost595
With 5 and 123 seed: @sim.inner.tree(outer): Error in .rexp.coal(k, comp, current.time) : 
  Error in rexp.coal: called on Compartment with <2 lineages.

``` InitialConditions:
  originTime: 10.0
  size:
    host: 100
  indexType: 'host'

CompartmentTypes:
  'host':
    branching.rates: (host=0.01)
    migration.rates: ()
    transition.rates: ()
    effective.size: 100.0
    generation.time: 1
    bottleneck.size: 1                 
    wait.time.distr:                   
      distr: 'exp'
      hyperparameters:
        rate: 20

Compartments:
  'I':
    type: host
    replicates: 1 or 2 or 5
    
Lineages:
  'virus1':
    sampling.time: (0, 2.0, 3.0)            
    location: I
    replicates: 3 ```

**Comment by RouxCil** [comment]
@ArtPoon Choose 1, 2 or 5 in the Compartments section in the posted yaml:

From
```
Compartments:
  'I':
    type: host
    replicates: 1 or 2 or 5
```
To
```
Compartments:
  'I':
    type: host
    replicates: 5
```

**Comment by ArtPoon** [comment]
I'm guessing the problem lives somewhere around here:
https://github.com/PoonLab/twt/blob/7a03ee236c3faa095b74d9ab3a186283906c3ad2/R/Model.R#L343

**Comment by ArtPoon** [comment]
* As described by @GopiGugan, this is an edge case where three lineages have been sampled from the same compartment (deme/cell), so the stopping condition is immediately met and we exit the loop with an empty event log
* expected behaviour should be outputting a tree of a single branch (basically the root), so that we can simulate the lineages within that branch until we converge to their common ancestor.
* possible solution (?) given an empty event log, `sim.outer.tree` should return a tree of one branch

**Comment by ArtPoon** [comment]
Using the above YAML, this script:
```R
require(twt)

settings <- yaml.load_file("~/git/twt/working/iss131.yaml")
model <- Model$new(settings)

set.seed(1)
run <- sim.outer.tree(model)
run$get.eventlog()

tree <- sim.inner.tree(run)
```
results in the following error:
```
Error in .rexp.coal(k, comp, current.time) : 
  Error in rexp.coal: called on Compartment with <2 lineages.
```

**Comment by ArtPoon** [comment]
This works:
```yaml
InitialConditions:
  originTime: 10.0
  size:
    host: 100
  indexType: 'host'

CompartmentTypes:
  'host':
    branching.rates: (host=0.01)
    migration.rates: ()
    transition.rates: ()
    effective.size: 100.0
    generation.time: 1
    bottleneck.size: 1                 
    wait.time.distr:                   
      distr: 'exp'
      hyperparameters:
        rate: 20

Compartments:
  'I1':
    type: host
  'I2':
    type: host

Lineages:
  'virus1':
    sampling.time: 3
    location: I1
    replicates: 1
  'virus2':
    sampling.time: 0
    location: I2
    replicates: 1
```

but changing this:
```yaml
Lineages:
  'virus1':
    sampling.time: 3
    location: I1
    replicates: 2
```
fails with the `rexp.coal` error.

**Comment by ArtPoon** [comment]
This doesn't work either:
```yaml
Lineages:
  'virus11':
    sampling.time: 3
    location: I1
    replicates: 1
  'virus12':
    sampling.time: 3
    location: I1
    replicates: 1
```
