### ISSUE TITLE
Odd sampling time behaviour

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/twt#132]
I have set up a simulation where I have a CompartmentType where transmissions only occur prior to simulation time 14 (see plot). 

<img width="866" alt="Screenshot 2022-02-10 at 11 38 42" src="https://user-images.githubusercontent.com/6604824/153453791-649d31ab-36f5-4fc1-8429-68ba22cbf49d.png">

If I try and sample lineages from this CompartmentType at simulation time 14 or 13 I get error: 

```
Error in .assign.events(run, events) : 
  Error in .assign.events(): No eligible compartments for transmission event 12.01968276234141Population2Population21218899
```
However sampling at simulation time 12 is fine despite there being no new transmission between time 14-12

```
set.seed(123)
path <- '~/Documents/1_projects/bayroot/Simulated_integration.yaml'
model <- Model$new(yaml.load_file(path))

outer <- sim.outer.tree(model)

plot(outer, type='s')
```

```
InitialConditions:
  originTime: 20.0
  size:
    Population1: 100
    Population2: 100
  indexType: 'Population1'

CompartmentTypes:
  'Population1':
    branching.rates: 
      20: (Population1=0.01, Population2=0.0)
      14: (Population1=0.0, Population2=0.01)
    migration.rates: ()
    transition.rates: ()
    effective.size: 100.0
    generation.time: 1
    bottleneck.size: 1                 
    wait.time.distr:                   
      distr: 'exp'
      hyperparameters:
        rate: 20

  'Population2':
    branching.rates: (Population1=0.0, Population2=0.01)
    migration.rates: ()
    transition.rates: ()
    effective.size: 100.0
    generation.time: 1
    bottleneck.size: 1                 
    wait.time.distr:                   
      distr: 'exp'
      hyperparameters:
        rate: 20

Compartments:
  'Population1I':
    type: Population1
    replicates: 2

  'Population2I':
    type: Population2
    replicates: 2

Lineages:
  'virus1':
    sampling.time: 14 or 13 or 12            
    location: Population1I
    replicates: 1

  'virus2':
    sampling.time: 0            
    location: Population2I
    replicates: 1
```
