### ISSUE TITLE
Failing unit test associated with load.origin.times

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#59]
```
── 1. Error: (unknown) (@test_classes.R#5)  ────────────────────────────────────
number of items to replace is not a multiple of replacement length
1: MODEL$new(settings) at /home/art/git/treeswithintrees/pkg/tests/testthat/test_classes.R:5
2: .subset2(public_bind_env, "initialize")(...)
3: private$load.origin.times(settings) at /home/art/git/treeswithintrees/pkg/R/loadInputs.R:26
```
Looks like `test.yaml` is using an outdated format:
```yaml
OriginTimes:
  'virus':
    start: 10.0                        # note this is reverse time, cumulative
CompartmentTypes:
  'host':
    susceptible: 1000
    branching.rates: (host=0.1)    
```
whereas `example1.yaml` stores `susceptible` field under heading `OriginTimes`:
```yaml
OriginTimes:
  'virus':                          # origin time of `virus` epidemic
    start: 10.0                     # note this is reverse time, cumulative
    susceptibles:
      - host: 1000   
```
