### ISSUE TITLE
Refactor OriginTime specification

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#73]
Previous scheme:
```yaml
OriginTimes:
  'virus':                          # origin time of `virus` epidemic
    start: 10.0                     # note this is reverse time, cumulative
    susceptibles:
      - host: 1000                  # number of susceptible at the origin time of the simulation for Type `host`
```

Proposed scheme:
```yaml
InitialConditions:
  originTime: 10.0
  popSize:
    host: 1000
  indexType: 'host'
```

* rename `OriginTimes` with `InitialConditions` as this field includes population sizes and compartment type
* rename `start` to `originTime`
* documentation needs to clarify that index case is subtracted from population size (`popSize`) of the corresponding CompartmentType.
* named list for `susceptibles` required two layers of indexing to access values.
* eliminating `LineageType` for now until we have decided how these will be handled.
