### ISSUE TITLE
Implement time-heterogeneous rates for CompartmentTypes

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#89]
For example, the branching rate of a CompartmentType may switch at a given time point for the entire population.
Currently we specify branching rate as 
```yaml
CompartmentTypes:
  host:
      branching.rate: 1.0
```

We may alter this to:
```yaml
CompartmentTypes:
  host:
      branching.rate:
          - 0: 1.0
          - 2.5: 0.5
```
so this rate is 1.0 at the start of forward-time simulation, and then switches from 1.0 to 0.5 at t=2.5.
